# DB setting
spring:
  application:
    name: shoppingMall
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.fubzffduvwgkmwratshu
    password: 1!2@3#4$qwer
    hikari:
      schema: shoppingMall
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 200000
      connection-timeout: 30000
  redis:
    host: redis-18049.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
    port: 18049
    password: CRSnzFHeElWF90SRVcShHO2GWs99T0oX
  session:
    store-type: redis
    timeout: 1800

# MyBatis
mybatis:
  mapper-locations: classpath:mappers/*.xml

# Server Port
server:
  port: 8081

# Logging
logging:
  level:
    org:
      springframework: DEBUG
    com:
      example: DEBUG
