# DB setting
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: shoppingMall
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: shoppingMall
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 200000
      connection-timeout: 30000
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  session:
    store-type: redis
    timeout: 1800

# MyBatis
mybatis:
  mapper-locations: classpath:mappers/*.xml

# Server Port
server:
  port: 8081

# Logging
logging:
  level:
    org:
      springframework: DEBUG
    com:
      example: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access_token_expiration: 360000
  refresh_token_expiration: 3600000

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}